if(EXISTS "/workspaces/coverage-gt/.build/goo_test[1]_tests.cmake")
  include("/workspaces/coverage-gt/.build/goo_test[1]_tests.cmake")
else()
  add_test(goo_test_NOT_BUILT goo_test_NOT_BUILT)
endif()
